# Generated by Django 4.2.4 on 2023-08-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtyManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to='image_manager')),
            ],
        ),
    ]
