# Generated by Django 4.2.4 on 2023-09-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtys', '0003_realty'),
    ]

    operations = [
        migrations.AddField(
            model_name='realty',
            name='header',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='realty',
            name='s',
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
    ]
