# Generated by Django 4.2.4 on 2023-09-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtys', '0004_realty_header_alter_realty_s'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
                ('from_email', models.CharField(max_length=50)),
                ('recepient', models.CharField(max_length=100)),
            ],
        ),
    ]
