# Generated by Django 4.2.4 on 2023-09-14 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtys', '0006_bill_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='recepient',
        ),
    ]
