# Generated by Django 4.2.4 on 2023-09-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtys', '0007_remove_bill_recepient'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='email_manager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
