# Generated by Django 4.2.4 on 2023-10-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtys', '0009_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='realty',
            name='sale',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
    ]
