# Generated by Django 4.2.4 on 2023-11-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtys', '0011_alter_realty_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_now', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='realty',
            name='sale',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True),
        ),
    ]
